SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
WHERE FAVORITES = (
    SELECT MAX(B.FAVORITES)
    FROM REST_INFO B
    WHERE A.FOOD_TYPE = B.FOOD_TYPE
)
-- GROUP BY A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
ORDER BY A.FOOD_TYPE DESC