SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
-- 보호소에 들어올 당시에는 중성화되지 않았지만 
-- 보호소를 나갈 당시에는 중성화된 동물
WHERE A.SEX_UPON_INTAKE LIKE 'Intact %' AND
(B.SEX_UPON_OUTCOME LIKE 'Neutered %' OR 
B.SEX_UPON_OUTCOME LIKE 'Spayed %')
ORDER BY B.ANIMAL_ID ASC