SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT B.USER_ID) AS USERS -- 년, 월, 성별, 회원수
FROM USER_INFO A JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
HAVING A.GENDER = 0 OR A.GENDER = 1 -- 성별정보가 없는 경우 제외
ORDER BY YEAR, MONTH, A.GENDER ASC -- 년, 월, 성별 오름차순