/*
  입양기록은 있지만 보호소에 들어온 기록이 없는 동물ID 출력
  ID 순으로 오름차순
*/
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL -- AND B.ANIMAL_ID IS NOT NULL
ORDER BY A.ANIMAL_ID