SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME IS NULL
ORDER BY A.ANIMAL_ID ASC
-- 입양을 간 기록은 있고, B.DATETIME
-- 보호소에 들어온 기록이 없는 A.DATETIME