SELECT A.FLAVOR AS FLAVOR
FROM FIRST_HALF A JOIN JULY B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
HAVING SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER)
ORDER BY SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC
LIMIT 3
-- A.TOTAL_ORDER과 B.TOTAL_ORDER을 더해서 큰 순서대로 3개만 조회