SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES -- 총 거래액
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME
HAVING SUM(A.PRICE) >= 700000 -- 중고 거래의 총금액이 70만 원 이상
ORDER BY SUM(A.PRICE) ASC; -- 총거래금액을 기준으로 오름차순 정렬