SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = '세단' AND
MONTH(START_DATE) = 10 -- WHERE 자동차종류 = '세단', 10월에 대여
ORDER BY A.CAR_ID DESC