SELECT B.INGREDIENT_TYPE, SUM(A.TOTAL_ORDER)
FROM FIRST_HALF A JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
-- 상반기 동안 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량을 총주문량이 작은 순서대로 조회 (총주문량 컬럼명은 TOTAL_ORDER)
-- INGREDIENT_TYPE