# 아이스크림 성분 타입, 성분타입에 대한 아이스크림 총주문량
SELECT B.INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF A JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
# 총주문량이 작은 순서대로
ORDER BY TOTAL_ORDER