SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE (CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '식용유' OR CATEGORY = '김치')
AND PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT
        WHERE CATEGORY = A.CATEGORY
)
ORDER BY MAX_PRICE DESC